https://www.youtube.com/watch?v=iaZQF8SLHJs&t=51s

In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("espn cricket.xlsx")
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [3]:
df.head(5)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6

In [4]:
df.shape

(65, 15)

In [6]:
df.columns

Index(['Player',   'Span',    'Mat',   'Inns',     'NO',   'Runs',     'HS',
          'Ave',     'BF',     'SR',      100,       50,        0,     '4s',
           '6s'],
      dtype='object')

In [10]:
df.index

RangeIndex(start=0, stop=65, step=1)

In [11]:
#rename multiple columns for a better understanding

df=df.rename(columns={"NO":"NOT_OUT",
                      "HS":"HIGHEST_SCORE",
                     "BF":"BALL_FACED",
                     "SR":"STRIKE_RATES",
                     "MAT":"MATCHES"})
df

,Player,Span,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [13]:
#check null value

df.isnull().any()

Player           False
Span             False
Mat              False
Inns             False
NOT_OUT          False
Runs             False
HIGHEST_SCORE    False
Ave              False
BALL_FACED       False
STRIKE_RATES      True
100              False
50               False
0                False
4s               False
6s               False
dtype: bool

In [14]:
#as above code shows that STRIKE_RATES has a null value, to see that null value row
df[df["STRIKE_RATES"].isna()==True]

,Player,Span,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s
7,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,4957,NaN,15,19,6,258+,2

In [19]:
#to fix it
df["STRIKE_RATES"]=df["STRIKE_RATES"].fillna(0)
df.isnull().sum() #so now no more null value is the dataframe

Player           0
Span             0
Mat              0
Inns             0
NOT_OUT          0
Runs             0
HIGHEST_SCORE    0
Ave              0
BALL_FACED       0
STRIKE_RATES     0
100              0
50               0
0                0
4s               0
6s               0
dtype: int64

In [21]:
df[df["Player"]=="ED Weekes (WI)"] #now see 0 filled inside the null value

,Player,Span,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s
7,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,4957,0.0,15,19,6,258+,2

In [23]:
df=df.drop_duplicates()
df

,Player,Span,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [25]:
#split up span into start and end date

df[["starting_year","last_year"]]=df["Span"].str.split("-",expand=True)
df

C:\Users\atrey\AppData\Local\Temp\ipykernel_15392\1097675551.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["starting_year","last_year"]]=df["Span"].str.split("-",expand=True)
C:\Users\atrey\AppData\Local\Temp\ipykernel_15392\1097675551.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["starting_year","last_year"]]=df["Span"].str.split("-",expand=True)

,Player,Span,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [27]:
df=df.drop(columns="Span")

In [29]:
#removing country code from the player column

df["Player"].str.split("(",expand=True)

               0        1
0    DG Bradman      AUS)
1      AC Voges      AUS)
2    RG Pollock       SA)
3    GA Headley       WI)
4   H Sutcliffe      ENG)
..           ...      ...
60   KD Walters      AUS)
61     GC Smith   ICC/SA)
62  WH Ponsford      AUS)
63    SJ McCabe      AUS)
64   DR Jardine      ENG)

[62 rows x 2 columns]

In [31]:
df["Player"].str.split("(").str[0]
#spliting the player col, and assigning the 1st index value as player_name

0      DG Bradman
1        AC Voges
2      RG Pollock
3      GA Headley
4     H Sutcliffe
          ...
60     KD Walters
61       GC Smith
62    WH Ponsford
63      SJ McCabe
64     DR Jardine
Name: Player, Length: 62, dtype: object

In [33]:
df["Player_name"]=df["Player"].str.split("(").str[0]
df

,Player,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges
2,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock
3,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley
4,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters
61,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith
62,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford
63,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe
64,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine

In [35]:
df["country"]=df["Player"].str.split("(").str[1]
df

,Player,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman,AUS)
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
2,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA)
3,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley,WI)
4,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe,ENG)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS)
61,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
62,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS)
63,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS)
64,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG)

In [37]:
df=df.drop(columns="Player",axis=0)
df

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country
0,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman,AUS)
1,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
2,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA)
3,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley,WI)
4,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe,ENG)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS)
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
62,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS)
63,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS)
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG)

In [39]:
df.dtypes

Mat                int64
Inns               int64
NOT_OUT            int64
Runs               int64
HIGHEST_SCORE     object
Ave              float64
BALL_FACED        object
STRIKE_RATES     float64
100                int64
50                 int64
0                  int64
4s                object
6s                object
starting_year     object
last_year         object
Player_name       object
country           object
dtype: object

In [104]:
#now see the highest score is a object dtypes and we want to remove the *,and convert it into int

df['HIGHEST_SCORE']=df['HIGHEST_SCORE'].apply(lambda x: x.replace('*', '') if isinstance(x, str) else x)
#The lambda function checks if the element is a string (isinstance(x, str)). If it is, it replaces "*"
#with an empty string (x.replace('*', '')). If it's not a string (e.g., NaN), it leaves the element unchanged (else x).                          
df

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country
0,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman,AUS)
1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
2,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA)
3,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley,WI)
4,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe,ENG)
5,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,E Paynter,ENG)
6,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591+,27,1955,1968,KF Barrington,ENG)
7,48,81,5,4455,207,58.61,4957,0.00,15,19,6,258+,2,1948,1958,ED Weekes,WI)
8,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,WR Hammond,ENG)
9,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,GS Sobers,WI)
10,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL)
12,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS)
13,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,JB Hobbs,ENG)
14,21,35,1,1931,317,56.79,2201,87.73,6,9,1,215,29,2022,2024,HC Brook,ENG)
15,44,74,7,3798,220,56.68,2844+,0.00,15,14,1,107+,11,1948,1960,CL Walcott,WI)
16,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,L Hutton,ENG)
17,14,26,1,1407,214,56.28,2006,70.13,3,8,1,163,35,2023,2024,YBK Jaiswal,IND)
18,15,28,3,1406,208,56.24,2911,48.29,4,7,1,143,1,2022,2024,Saud Shakeel,PAK)
19,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA)
20,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,GE Tyldesley,ENG)
21,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26,2010,2024,KS Williamson,NZ)
22,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,CA Davis,WI)
23,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND)
24,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS)
25,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,AD Nourse,SA)
26,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,SR Tendulkar,IND)
27,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI)
28,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,Javed Miandad,PAK)
30,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND)
31,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK)
32,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK)
33,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS)
34,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,J Ryder,AUS)
35,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM)
36,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS)
37,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI)
38,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,SM Gavaskar,IND)
39,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS)
40,149,272,22,12754,262,51.01,22306,57.17,35,64,12,1364,44,2012,2024,JE Root,ENG)
41,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS)
42,17,26,2,1185,182,49.37,619+,30.04,4,3,3,38+,0,1911,1928,CP Mead,ENG)
43,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA)
44,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS)
45,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991,IVA Richards,WI)
46,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957,DCS Compton,ENG)
47,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL)
48,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK)
49,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS)
50,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963,FMM Worrell,WI)
52,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND)
53,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK)
54,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS)
55,21,39,5,1669,144,49.08,885+,37.74,3,9,2,123+,20,1961,1966,KC Bland,SA)
56,42,80,9,3471,189,48.88,158+,29.11,8,21,3,41+,1,1929,1949,B Mitchell,SA)
57,20,33,4,1415,144,48.79,-,0.00,5,6,3,51+,0,1893,1905,Hon.FS Jackson,ENG)
58,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL)
59,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963,RN Harvey,AUS)
60,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS)
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
62,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS)
63,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS)
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG)

#if any columns consist of this kind of issue, then we can do like above code

for i in df["HIGHEST_SCORE"]:
    if  isinstance(i,str) and "*" in i:
        print(i)

Check if the Entry is a String: The isinstance(i, str) check ensures that only string values are checked for the presence of "*". This prevents the error you encountered.

In [70]:
df["HIGHEST_SCORE"]=df["HIGHEST_SCORE"].astype("int")
df.dtypes

Mat                int64
Inns               int64
NOT_OUT            int64
Runs               int64
HIGHEST_SCORE      int32
Ave              float64
BALL_FACED        object
STRIKE_RATES     float64
100                int64
50                 int64
0                  int64
4s                object
6s                object
starting_year     object
last_year         object
Player_name       object
country           object
dtype: object

In [78]:
#converting data types of columns in a one go 

df=df.astype({"starting_year":"int",
             "last_year":"int",
             })
df

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country
0,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman,AUS)
1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
2,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA)
3,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley,WI)
4,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe,ENG)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS)
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
62,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS)
63,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS)
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG)

In [92]:
pd.set_option("display.max_rows",None)
df

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country
0,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman,AUS)
1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
2,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA)
3,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley,WI)
4,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe,ENG)
5,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,E Paynter,ENG)
6,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591+,27,1955,1968,KF Barrington,ENG)
7,48,81,5,4455,207,58.61,4957,0.00,15,19,6,258+,2,1948,1958,ED Weekes,WI)
8,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,WR Hammond,ENG)
9,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,GS Sobers,WI)
10,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL)
12,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS)
13,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,JB Hobbs,ENG)
14,21,35,1,1931,317,56.79,2201,87.73,6,9,1,215,29,2022,2024,HC Brook,ENG)
15,44,74,7,3798,220,56.68,2844+,0.00,15,14,1,107+,11,1948,1960,CL Walcott,WI)
16,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,L Hutton,ENG)
17,14,26,1,1407,214,56.28,2006,70.13,3,8,1,163,35,2023,2024,YBK Jaiswal,IND)
18,15,28,3,1406,208,56.24,2911,48.29,4,7,1,143,1,2022,2024,Saud Shakeel,PAK)
19,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA)
20,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,GE Tyldesley,ENG)
21,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26,2010,2024,KS Williamson,NZ)
22,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,CA Davis,WI)
23,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND)
24,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS)
25,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,AD Nourse,SA)
26,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,SR Tendulkar,IND)
27,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI)
28,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,Javed Miandad,PAK)
30,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND)
31,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK)
32,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK)
33,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS)
34,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,J Ryder,AUS)
35,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM)
36,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS)
37,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI)
38,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,SM Gavaskar,IND)
39,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS)
40,149,272,22,12754,262,51.01,22306,57.17,35,64,12,1364,44,2012,2024,JE Root,ENG)
41,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS)
42,17,26,2,1185,182,49.37,619+,30.04,4,3,3,38+,0,1911,1928,CP Mead,ENG)
43,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA)
44,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS)
45,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991,IVA Richards,WI)
46,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957,DCS Compton,ENG)
47,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL)
48,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK)
49,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS)
50,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963,FMM Worrell,WI)
52,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND)
53,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK)
54,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS)
55,21,39,5,1669,144,49.08,885+,37.74,3,9,2,123+,20,1961,1966,KC Bland,SA)
56,42,80,9,3471,189,48.88,158+,29.11,8,21,3,41+,1,1929,1949,B Mitchell,SA)
57,20,33,4,1415,144,48.79,-,0.00,5,6,3,51+,0,1893,1905,Hon.FS Jackson,ENG)
58,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL)
59,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963,RN Harvey,AUS)
60,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS)
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
62,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS)
63,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS)
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG)

In [110]:
#now we removing + from the BALL_FACED

df.dropna() #droping nan values
df.replace("-","") # to replace "-", by ""
df.isnull().any() #to check if any null present 

df['BALL_FACED'] = df['BALL_FACED'].apply(lambda x: x.strip("+") if isinstance(x, str) else x)
#isinstance(x, str): Check if x is a string,x.strip("+"): Remove the "+" character from the string.

#df["BALL_FACED"].astype("int")
df

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626+,6,1928,1948,DG Bradman,AUS)
1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
2,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA)
3,22,40,4,2190,270,60.83,416,56.00,10,5,2,104+,1,1930,1954,GA Headley,WI)
4,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe,ENG)
5,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125+,4,1931,1939,E Paynter,ENG)
6,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591+,27,1955,1968,KF Barrington,ENG)
7,48,81,5,4455,207,58.61,4957,0.00,15,19,6,258+,2,1948,1958,ED Weekes,WI)
8,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419+,27,1927,1947,WR Hammond,ENG)
9,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593+,32+,1954,1974,GS Sobers,WI)
10,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL)
12,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS)
13,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276+,8,1908,1930,JB Hobbs,ENG)
14,21,35,1,1931,317,56.79,2201,87.73,6,9,1,215,29,2022,2024,HC Brook,ENG)
15,44,74,7,3798,220,56.68,2844,0.00,15,14,1,107+,11,1948,1960,CL Walcott,WI)
16,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358+,7,1937,1955,L Hutton,ENG)
17,14,26,1,1407,214,56.28,2006,70.13,3,8,1,163,35,2023,2024,YBK Jaiswal,IND)
18,15,28,3,1406,208,56.24,2911,48.29,4,7,1,143,1,2022,2024,Saud Shakeel,PAK)
19,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA)
20,14,20,2,990,122,55.00,178,29.21,3,6,2,37+,2,1921,1929,GE Tyldesley,ENG)
21,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26,2010,2024,KS Williamson,NZ)
22,15,29,5,1301,183,54.20,665,35.48,4,4,1,65+,1,1968,1973,CA Davis,WI)
23,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND)
24,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS)
25,34,62,7,2960,231,53.81,108,63.88,9,14,3,115+,6,1935,1951,AD Nourse,SA)
26,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058+,69,1989,2013,SR Tendulkar,IND)
27,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI)
28,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788+,48,1976,1993,Javed Miandad,PAK)
30,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND)
31,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK)
32,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK)
33,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS)
34,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102+,3,1920,1929,J Ryder,AUS)
35,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM)
36,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS)
37,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI)
38,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908+,26,1971,1987,SM Gavaskar,IND)
39,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS)
40,149,272,22,12754,262,51.01,22306,57.17,35,64,12,1364,44,2012,2024,JE Root,ENG)
41,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS)
42,17,26,2,1185,182,49.37,619,30.04,4,3,3,38+,0,1911,1928,CP Mead,ENG)
43,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA)
44,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS)
45,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952+,84,1974,1991,IVA Richards,WI)
46,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342+,3,1937,1957,DCS Compton,ENG)
47,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL)
48,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK)
49,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS)
50,51,87,9,3860,261,49.48,488,40.16,9,22,11,240+,11,1948,1963,FMM Worrell,WI)
52,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND)
53,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK)
54,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS)
55,21,39,5,1669,144,49.08,885,37.74,3,9,2,123+,20,1961,1966,KC Bland,SA)
56,42,80,9,3471,189,48.88,158,29.11,8,21,3,41+,1,1929,1949,B Mitchell,SA)
57,20,33,4,1415,144,48.79,-,0.00,5,6,3,51+,0,1893,1905,Hon.FS Jackson,ENG)
58,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL)
59,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427+,1,1948,1963,RN Harvey,AUS)
60,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS)
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
62,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS)
63,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS)
64,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG)

In [114]:
#REMOVING + FROM THE 4S col
df["4s"]=df["4s"].apply(lambda x: x.strip("+") if isinstance(x,str) else x)

In [118]:
#removing ) from the country 
df["country"]=df["country"].apply(lambda x: x.strip(")") if isinstance(x,str) else x)

In [120]:
df

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,DG Bradman,AUS
1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS
2,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,RG Pollock,SA
3,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,GA Headley,WI
4,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,H Sutcliffe,ENG
5,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,E Paynter,ENG
6,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,KF Barrington,ENG
7,48,81,5,4455,207,58.61,4957,0.00,15,19,6,258,2,1948,1958,ED Weekes,WI
8,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,WR Hammond,ENG
9,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32+,1954,1974,GS Sobers,WI
10,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL
12,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS
13,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,JB Hobbs,ENG
14,21,35,1,1931,317,56.79,2201,87.73,6,9,1,215,29,2022,2024,HC Brook,ENG
15,44,74,7,3798,220,56.68,2844,0.00,15,14,1,107,11,1948,1960,CL Walcott,WI
16,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,L Hutton,ENG
17,14,26,1,1407,214,56.28,2006,70.13,3,8,1,163,35,2023,2024,YBK Jaiswal,IND
18,15,28,3,1406,208,56.24,2911,48.29,4,7,1,143,1,2022,2024,Saud Shakeel,PAK
19,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA
20,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,GE Tyldesley,ENG
21,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26,2010,2024,KS Williamson,NZ
22,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,CA Davis,WI
23,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND
24,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS
25,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,AD Nourse,SA
26,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,SR Tendulkar,IND
27,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI
28,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,Javed Miandad,PAK
30,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND
31,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK
32,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK
33,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS
34,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,J Ryder,AUS
35,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM
36,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS
37,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI
38,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,SM Gavaskar,IND
39,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS
40,149,272,22,12754,262,51.01,22306,57.17,35,64,12,1364,44,2012,2024,JE Root,ENG
41,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS
42,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,CP Mead,ENG
43,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA
44,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS
45,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,IVA Richards,WI
46,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,DCS Compton,ENG
47,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL
48,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK
49,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS
50,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,FMM Worrell,WI
52,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND
53,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK
54,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS
55,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966,KC Bland,SA
56,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,B Mitchell,SA
57,20,33,4,1415,144,48.79,-,0.00,5,6,3,51,0,1893,1905,Hon.FS Jackson,ENG
58,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL
59,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,RN Harvey,AUS
60,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,KD Walters,AUS
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA
62,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,WH Ponsford,AUS
63,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5+,1930,1938,SJ McCabe,AUS
64,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,DR Jardine,ENG

In [122]:
#carrer lenght of any player

df["carrer_lenght"]=df["last_year"]-df["starting_year"]
df

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country,carrer_lenght
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,DG Bradman,AUS,20
1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS,1
2,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,RG Pollock,SA,7
3,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,GA Headley,WI,24
4,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,H Sutcliffe,ENG,11
5,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,E Paynter,ENG,8
6,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,KF Barrington,ENG,13
7,48,81,5,4455,207,58.61,4957,0.00,15,19,6,258,2,1948,1958,ED Weekes,WI,10
8,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,WR Hammond,ENG,20
9,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32+,1954,1974,GS Sobers,WI,20
10,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL,15
12,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS,14
13,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,JB Hobbs,ENG,22
14,21,35,1,1931,317,56.79,2201,87.73,6,9,1,215,29,2022,2024,HC Brook,ENG,2
15,44,74,7,3798,220,56.68,2844,0.00,15,14,1,107,11,1948,1960,CL Walcott,WI,12
16,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,L Hutton,ENG,18
17,14,26,1,1407,214,56.28,2006,70.13,3,8,1,163,35,2023,2024,YBK Jaiswal,IND,1
18,15,28,3,1406,208,56.24,2911,48.29,4,7,1,143,1,2022,2024,Saud Shakeel,PAK,2
19,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA,18
20,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,GE Tyldesley,ENG,8
21,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26,2010,2024,KS Williamson,NZ,14
22,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,CA Davis,WI,5
23,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND,2
24,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS,14
25,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,AD Nourse,SA,16
26,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,SR Tendulkar,IND,24
27,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI,16
28,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,Javed Miandad,PAK,17
30,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND,16
31,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK,12
32,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK,17
33,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS,17
34,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,J Ryder,AUS,9
35,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM,10
36,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS,8
37,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI,21
38,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,SM Gavaskar,IND,16
39,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS,19
40,149,272,22,12754,262,51.01,22306,57.17,35,64,12,1364,44,2012,2024,JE Root,ENG,12
41,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS,15
42,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,CP Mead,ENG,17
43,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA,14
44,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS,16
45,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,IVA Richards,WI,17
46,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,DCS Compton,ENG,20
47,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL,17
48,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK,15
49,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS,6
50,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,FMM Worrell,WI,15
52,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND,12
53,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK,2
54,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS,11
55,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966,KC Bland,SA,5
56,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,B Mitchell,SA,20
57,20,33,4,1415,144,48.79,-,0.00,5,6,3,51,0,1893,1905,Hon.FS Jackson,ENG,12
58,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL,12
59,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,RN Harvey,AUS,15
60,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,KD Walters,AUS,16
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA,12
62,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,WH Ponsford,AUS,10
63,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5+,1930,1938,SJ McCabe,AUS,8
64,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,DR Jardine,ENG,6

In [124]:
#avg career length of all players

df["carrer_lenght"].mean()

12.96774193548387

In [128]:
#avg batting strike rate ,thoes who play more than 10 years
df[df["carrer_lenght"]>10]["STRIKE_RATES"].mean()

47.785348837209305

In [132]:
#find number of player played before 1950
df[df["last_year"]<1950]

,Mat,Inns,NOT_OUT,Runs,HIGHEST_SCORE,Ave,BALL_FACED,STRIKE_RATES,100,50,0,4s,6s,starting_year,last_year,Player_name,country,carrer_lenght
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,DG Bradman,AUS,20
4,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,H Sutcliffe,ENG,11
5,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,E Paynter,ENG,8
8,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,WR Hammond,ENG,20
13,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,JB Hobbs,ENG,22
20,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,GE Tyldesley,ENG,8
34,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,J Ryder,AUS,9
42,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,CP Mead,ENG,17
56,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,B Mitchell,SA,20
57,20,33,4,1415,144,48.79,-,0.00,5,6,3,51,0,1893,1905,Hon.FS Jackson,ENG,12
62,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,WH Ponsford,AUS,10
63,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5+,1930,1938,SJ McCabe,AUS,8
64,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,DR Jardine,ENG,6

In [146]:
#4 max highest score by country
df.groupby("country")["HIGHEST_SCORE"].max()
df.sort_values(ascending=False)

country
ICC/WI     400
AUS        380
SL         374
WI         365
ENG        364
ICC/PAK    329
ICC/IND    319
PAK        313
SA         278
ICC/SA     277
NZ         251
IND        248
ZIM        232
Name: HIGHEST_SCORE, dtype: int64

In [162]:
df.columns

Index([          'Mat',          'Inns',       'NOT_OUT',          'Runs',
       'HIGHEST_SCORE',           'Ave',    'BALL_FACED',  'STRIKE_RATES',
                   100,              50,               0,            '4s',
                  '6s', 'starting_year',     'last_year',   'Player_name',
             'country', 'carrer_lenght'],
      dtype='object')

In [172]:
# hundred,fifties,ducks (0) avg by country

df.groupby('country')[[100,50,0.]].mean()

               100         50          0
country
AUS      20.625000  28.375000   8.562500
ENG      12.846154  21.230769   4.307692
ICC/IND  29.500000  47.500000  12.000000
ICC/PAK  25.000000  46.000000  15.000000
ICC/SA   36.000000  48.000000  13.500000
ICC/WI   34.000000  48.000000  17.000000
IND      23.000000  31.000000   7.500000
NZ       32.000000  35.000000  11.000000
PAK      17.800000  23.800000   7.800000
SA        9.800000  20.200000   3.400000
SL       28.666667  44.000000  12.333333
WI       16.625000  25.625000   7.250000
ZIM      12.000000  27.000000   5.000000